name: Update Snake Animation

on:
  schedule: 
    - cron: "*/12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Generate Snake Animation
        run: npm run snake

      - name: Commit and push if changed
        run: |
          git diff --exit-code || {
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add dist/github-contribution-grid-snake.svg
            git commit -m "Update Snake Animation" || true
            git push
          }

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
